name: CI

on: [push, pull_request]
env:
  GOPROXY: https://proxy.golang.org
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Download Dependencies
        run: go mod download
      - name: Test
        run: make test
